package se.tink.core.models.authentication;

public enum AuthenticationStatus {
	UNRECOGNIZED,
	AUTHENTICATION_STATUS_UNKNOWN,
	AUTHENTICATION_STATUS_AUTHENTICATED,
	AUTHENTICATION_STATUS_AUTHENTICATION_ERROR,
	AUTHENTICATION_STATUS_NO_USER,
	AUTHENTICATION_STATUS_USER_BLOCKED,
	AUTHENTICATION_STATUS_AUTHENTICATED_UNAUTHORIZED_DEVICE
}
